# Pandas. Домашнее задание

В домашнем задании есть обязательные и дополнительные задачи.

*Обязательные задачи* нужно сделать, чтобы проверить, что вы действительно усвоили материал модуля. Они обязательны к загрузке на проверку преподавателю.

*Дополнительные задачи* для тех, кто чувствует, что нужно ещё немного потренироваться и порешать задачки по работе с Pandas. Вы также можете загрузить их на проверку преподавателю и получить по ним обратную связь.

Удачи!



---



---



**Цели домашнего задания:**
1. Научиться работать с описательными статистиками набора данных.
2. Научиться выбирать данные по условиям.
3. Научиться объединять несколько датафреймов в один.


**Что входит в домашнее задание:**
1. *Обязательные задачи*:

17 задач с использованием:
- набора рекламных данных, показывающих, щелкнул ли конкретный пользователь интернета рекламу на веб-сайте компании или нет,
- дополнительного набора данных, описывающего пользователей, посещающих веб-сайт компании.
2. *Дополнительные задачи*:

3 задачи для отработки исследования данных.


**Критерии оценки:**
- программа выдаёт верный ответ на заданном наборе данных;
- код читабелен: переменным даны осмысленные названия, отступы и правила расстановки пробелов соблюдены.

**Как отправить задание на проверку**

Выполните задачи, сохраните изменения при помощи опции Save and Checkpoint из вкладки меню File или кнопки Save and Checkpoint на панели инструментов. Отправьте через форму на платформе итоговый файл Jupyter Notebook (в формате .ipynb) или ссылку на него.



---


---



**Обязательные задачи**

В течение всего домашнего задания вы будете работать с несколькими наборами данных:
1. Набор рекламных данных, показывающих, щёлкнул ли конкретный пользователь рекламу на сайте компании или нет. Состоит из трёх разных файлов: `advertising_1.csv`, `advertising_2.csv`, `advertising_3.csv`.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Daily Time Spent on Site**: Среднее ежедневное время нахождения пользователя на сайте в минутах.
- **Daily Internet Usage**: Среднее ежедневное время нахождения пользователя в интернете в минутах.
- **Ad Topic Line**: Заголовок рекламного объявления.
- **Clicked on Ad**: Кликнул пользователь на рекламу или нет.

Дополнительный к рекламным данным датасет, который описывает пользователей, посещающих сайт компании. Состоит из одного файла: users.csv.

Описание столбцов датасета:
- **Number**: Номер пользователя в системе.
- **Age**: Возраст пользователя.
- **Male**: Является ли пользователь мужчиной.
- **City**: Город пользователя.
- **Country**: Страна пользователя.
- **Area Income**: Средний доход в месте жительства пользователя.


***Задача 1***

Загрузите таблицу из файла `advertising_1.csv` и сохраните её в датафрейм `adv1_df`. Укажите в качестве индекса столбец `Number`. Выведите на экран первые десять строк.


In [1]:
import pandas as pd
adv1_df = pd.read_csv('advertising_1.csv', index_col='Number')
adv1_df.head(10)

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
Number,,,,
5,68.95,256.09,Cloned 5thgeneration orchestration,0
6,80.23,193.77,Monitored national standardization,0
8,74.15,245.89,Triple-buffered reciprocal time-frame,0
9,NaN,225.58,Robust logistical utilization,0
10,59.99,226.74,Sharable client-driven software,0
11,88.91,208.36,Enhanced dedicated support,0
12,NaN,131.76,Reactive local challenge,1
13,74.53,NaN,Configurable coherent function,0
14,69.88,183.82,Mandatory homogeneous architecture,0


***Задача 2***

Выведите размер датафрейма `adv1_df`.

In [5]:
adv1_df.shape

(500, 4)

***Задача 3***

Выведите cреднее ежедневное время нахождения в интернете пользователя под номером 8.

In [21]:
adv1_df.loc[8, 'Daily Time Spent on Site']

np.float64(74.15)

***Задача 4***

Загрузите таблицу из файла `advertising_2.csv` и сохраните её в датафрейм `adv2_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран строки для пользователей с номерами с 533-го по 536-й.

In [6]:
adv2_df = pd.read_csv('advertising_2.csv', index_col='Number')
adv2_df.loc[533:536]

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
Number,,,,
533,46.61,NaN,Ergonomic methodical encoding,1
534,NaN,162.03,Compatible dedicated productivity,0
535,65.10,118.10,Up-sized real-time methodology,1
536,53.44,NaN,Up-sized next generation architecture,1


***Задача 5***

Выведите сводную таблицу описательных статистик для датафрейма `adv2_df`, вызвав необходимый метод на всём датафрейме.

Глядя на вывод, напишите, столбец с каким названием не содержит незаполненных значений.

*Подсказка:*  В сводной таблице не содержится информации о количестве строк всего датафрейма, поэтому для сначала распечатайте общее количество строк датафрейма.

*Рекомендация:* Кроме изученного метода `describe` для описания датафрейма и получения информации о пропущенных значениях полезен метод [`info`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html).

In [7]:
adv2_total_rows = len(adv2_df)
adv2_describe = adv2_df.describe(include='all')
full_columns_without_missing = [column for column in adv2_df.columns if adv2_df[column].notna().sum() == adv2_total_rows]

print('Количество строк в adv2_df:', adv2_total_rows)
display(adv2_describe)
print('Столбцы без пропусков:', full_columns_without_missing)

Количество строк в adv2_df: 200


,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
count,184.000000,184.000000,200,200.000000
unique,NaN,NaN,200,NaN
top,NaN,NaN,Re-engineered impactful software,NaN
freq,NaN,NaN,1,NaN
mean,66.494728,186.809674,NaN,0.420000
std,15.414725,43.844580,NaN,0.494797
min,32.910000,108.030000,NaN,0.000000
25%,52.805000,148.955000,NaN,0.000000
50%,71.150000,194.170000,NaN,0.000000
75%,78.352500,225.372500,NaN,1.000000


Столбцы без пропусков: ['Ad Topic Line', 'Clicked on Ad']


In [8]:
adv12_df = pd.concat([adv1_df, adv2_df])
adv12_df

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
Number,,,,
5,68.95,256.09,Cloned 5thgeneration orchestration,0
6,80.23,193.77,Monitored national standardization,0
8,74.15,245.89,Triple-buffered reciprocal time-frame,0
9,NaN,225.58,Robust logistical utilization,0
10,59.99,226.74,Sharable client-driven software,0
...,...,...,...,...
735,65.53,190.17,Pre-emptive client-server installation,0
736,61.87,NaN,Multi-channeled attitude-oriented toolset,0
737,83.16,NaN,Decentralized 24hour approach,0


***Задача 6***

Добавьте к датафрейму `adv1_df` в конец датафрейм `adv2_df` с помощью метода `concat`.

Сохраните объединенный датафрейм в новой переменной `adv12_df` и распечатайте его.

Документация по методу concat: [pandas.concat](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)

In [16]:

adv12_df = pd.concat([adv1_df, adv2_df], ignore_index=True)
adv12_df


,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
0,68.95,256.09,Cloned 5thgeneration orchestration,0
1,80.23,193.77,Monitored national standardization,0
2,74.15,245.89,Triple-buffered reciprocal time-frame,0
3,NaN,225.58,Robust logistical utilization,0
4,59.99,226.74,Sharable client-driven software,0
...,...,...,...,...
695,65.53,190.17,Pre-emptive client-server installation,0
696,61.87,NaN,Multi-channeled attitude-oriented toolset,0
697,83.16,NaN,Decentralized 24hour approach,0
698,44.11,121.24,Organic next generation matrix,1


***Задача 7***

Для объединённого датафрейма `adv12_df` распечатайте среднее время, проводимое пользователем на сайте компании.

In [20]:
avg_time = [adv12_df['Daily Time Spent on Site'].mean()]
print(avg_time)

[np.float64(65.57268138801263)]


***Задача 8***

Из объединённого датафрейма `adv12_df` выберите и распечатайте строки только с теми пользователями, для которых неизвестно среднее ежедневное время, проводимое пользователем на сайте компании.

In [24]:

users_missing_time = adv12_df[adv12_df['Daily Time Spent on Site'].isna()]
users_missing_time

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
3,NaN,225.58,Robust logistical utilization,0
6,NaN,131.76,Reactive local challenge,1
13,NaN,143.56,Grass-roots coherent extranet,1
20,NaN,164.83,Mandatory disintermediate utilization,1
27,NaN,209.82,Business-focused value-added definition,0
...,...,...,...,...
636,NaN,235.97,Customizable value-added project,0
638,NaN,126.44,Reactive impactful challenge,1
647,NaN,200.71,Focused multi-state workforce,0
652,NaN,226.69,Total coherent superstructure,0


***Задача 9***

Загрузите таблицу из файла `advertising_3.csv` и сохраните её в датафрейм `adv3_df`. Укажите в качестве индекса стоблец `Number`. Выведите на экран столбцы `Ad Topic Line` и `Clicked on Ad`.

In [25]:
adv3_df = pd.read_csv('advertising_3.csv', index_col='Number')
adv3_df[['Ad Topic Line', 'Clicked on Ad']]

,Ad Topic Line,Clicked on Ad
Number,,
740,Distributed bifurcated challenge,0
741,Customizable zero-defect Internet solution,0
742,Self-enabling zero administration neural-net,1
744,Open-architected system-worthy ability,0
745,Quality-focused maximized extranet,1
...,...,...
999,Front-line bifurcated ability,1
1000,Fundamental modular algorithm,1
1001,Grass-roots cohesive monitoring,1


***Задача 10***

Добавьте к датафрейму `adv12_df` в конец датафрейм `adv3_df` с помощью метода `concat`. Явно пропишите значение параметра `axis`.

Сохраните объединённый датафрейм в новой переменной `adv123_df` и распечатайте его.

In [28]:
adv123_df = pd.concat([adv12_df, adv3_df], axis=0)
adv123_df

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
0,68.95,256.09,Cloned 5thgeneration orchestration,0
1,80.23,193.77,Monitored national standardization,0
2,74.15,245.89,Triple-buffered reciprocal time-frame,0
3,NaN,225.58,Robust logistical utilization,0
4,59.99,226.74,Sharable client-driven software,0
...,...,...,...,...
999,43.70,173.01,Front-line bifurcated ability,1
1000,72.97,208.58,Fundamental modular algorithm,1
1001,51.30,NaN,Grass-roots cohesive monitoring,1
1002,51.63,120.37,Expanded intangible solution,1


***Задача 11***

Для объединённого датафрейма `adv123_df` выберите только те строки, в которых пользователи кликнули на рекламное сообщение. Сохраните полученный результат в датафрейм `success_adv_df`, распечатайте размер нового датафрейма.

In [29]:
success_adv_df = adv123_df[adv123_df['Clicked on Ad'] == 1]
success_adv_df.shape

(475, 4)

***Задача 12***

Загрузите таблицу с данными пользователей из файла `users.csv` и сохраните её в датафрейм `users_df`. Индекс не указывайте.

Распечатайте сам датафрейм и сводную таблицу со статистиками для него.

In [30]:
users_df = pd.read_csv('users.csv')
display(users_df)
users_df.describe(include='all')

,Number,Age,Male,City,Country,Area Income
0,5,NaN,0.0,Wrightburgh,Tunisia,61833.90
1,6,31.0,NaN,West Jodi,Nauru,68441.85
2,7,26.0,0.0,Davidton,San Marino,59785.94
3,8,29.0,1.0,West Terrifurt,Italy,54806.18
4,9,NaN,0.0,South Manuel,Iceland,73889.99
...,...,...,...,...,...,...
975,1000,30.0,NaN,Duffystad,Lebanon,71384.57
976,1001,45.0,1.0,New Darlene,Bosnia and Herzegovina,67782.17
977,1002,51.0,NaN,South Jessica,Mongolia,42415.72
978,1003,19.0,0.0,West Steven,Guatemala,41920.79


,Number,Age,Male,City,Country,Area Income
count,980.000000,860.000000,868.000000,887,888,903.000000
unique,NaN,NaN,NaN,860,235,NaN
top,NaN,NaN,NaN,Lisamouth,France,NaN
freq,NaN,NaN,NaN,3,9,NaN
mean,504.485714,36.073256,0.500000,NaN,NaN,55010.631938
std,287.956480,8.795992,0.500288,NaN,NaN,13423.710892
min,5.000000,19.000000,0.000000,NaN,NaN,13996.500000
25%,255.750000,29.000000,0.000000,NaN,NaN,46947.570000
50%,503.500000,35.000000,0.500000,NaN,NaN,57032.360000
75%,753.250000,42.000000,1.000000,NaN,NaN,65537.990000


***Задача 13***

Глядя на статистики `users_df`, укажите значения, удовлетворяющие следующим условиям:
1. Возраст самого молодого пользователя сайта: *ваш_ответ*
2. Максимальный средний доход в месте жительства пользователя сайта: *ваш_ответ*
3. Средний возраст пользователя сайта: *ваш_ответ*
4. Количество заполненных значений для колонки, содержащей информацию о том, является пользователь мужчиной или нет: *ваш_ответ*
5. Минимальный номер пользователя: *ваш_ответ*

В этом задании не требуется выбирать по условиям и распечатывать значения, достаточно внимательно посмотреть на статистики и скопировать нужные значения согласно вопросам.

In [31]:
print('1. Возраст самого молодого пользователя сайта:', users_df['Age'].min())
print('2. Максимальный средний доход в месте жительства пользователя сайта:', users_df['Area Income'].max())
print('3. Средний возраст пользователя сайта:', users_df['Age'].mean())
print('4. Количество заполненных значений для колонки Male:', users_df['Male'].count())
print('5. Минимальный номер пользователя:', users_df['Number'].min())

1. Возраст самого молодого пользователя сайта: 19.0
2. Максимальный средний доход в месте жительства пользователя сайта: 79484.8
3. Средний возраст пользователя сайта: 36.07325581395349
4. Количество заполненных значений для колонки Male: 868
5. Минимальный номер пользователя: 5


***Задача 14***

К полученному датафрейму с успешными рекламными сообщениями `success_adv_df` добавьте справа информацию из датафрейма с пользователями `users_df` и сохраните в датафрейм `success_full_df`. В полученном датафрейме должны остаться только те пользователи, номера которых есть в обоих датафреймах. Для этого воспользуйтесь методом `merge` и пропишите явно верные параметры.

Затем распечатайте датафрейм.

*Важно:*

Объединять датафреймы с помощью `merge` можно и по индексам, и по столбцам с разными названиями.
Так как общие значения содержатся в столбце `Number`, но в датафрейме `users_df` данный столбец является обычным столбцом, а в `success_adv_df` является индексом, перед тем как объединять, переведите столбец `Number` в `success_adv_df` в обычный столбец.

Для этого перед объединением пропишите:
```
success_adv_df = success_adv_df.reset_index()
```

[Подробнее о reset_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html)

In [50]:

success_adv_df['Number'] = success_adv_df.index

success_full_df = success_adv_df.merge(users_df, on='Number', how='inner')

print(success_full_df)

     level_0  index  Daily Time Spent on Site  Daily Internet Usage  \
0          5     15                     55.39                   NaN   
1          6     17                     74.58                135.51   
2          7     20                       NaN                164.83   
3          8     22                     41.39                   NaN   
4          9     24                     48.53                134.14   
..       ...    ...                       ...                   ...   
456      470    997                     69.17                123.62   
457      471    999                     43.70                173.01   
458      472   1000                     72.97                208.58   
459      473   1001                     51.30                   NaN   
460      474   1002                     51.63                120.37   

                             Ad Topic Line  Clicked on Ad  Number   Age  Male  \
0       Customizable multi-tasking website              1       5 

***Задача 15***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, отобразите сводную таблицу со статистиками для строковых колонок (`Ad Topic Line`, `City`, `Country`).


In [51]:
success_full_df[['Ad Topic Line', 'City', 'Country']].describe(include='all')

,Ad Topic Line,City,Country
count,461,414,414
unique,461,408,199
top,Customizable multi-tasking website,Wrightburgh,Czech Republic
freq,1,2,6


***Задача 16***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите страну и количество вхождений этой страны в датафрейм.


In [52]:
success_full_df['Country'].value_counts()

Country
Czech Republic               6
South Africa                 5
Bouvet Island (Bouvetoya)    5
Turks and Caicos Islands     5
Qatar                        5
                            ..
Palau                        1
New Zealand                  1
Netherlands                  1
Gibraltar                    1
Switzerland                  1
Name: count, Length: 199, dtype: int64

***Задача 17***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных.


In [53]:
top_country = success_full_df['Country'].value_counts().idxmax()
success_full_df[success_full_df['Country'] == top_country]

,level_0,index,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad,Number,Age,Male,City,Country,Area Income
99,108,206,49.95,136.59,Cloned object-oriented benchmark,1,108,21.0,1.0,Sanchezmouth,Czech Republic,48376.14
141,150,284,33.52,165.56,Vision-oriented optimizing middleware,1,150,44.0,1.0,Port Lawrence,Czech Republic,45716.48
212,223,444,65.59,121.81,Digitized disintermediate ability,1,223,40.0,0.0,Davilachester,Czech Republic,59621.02
331,344,755,61.82,151.93,Open-architected needs-based customer loyalty,1,344,NaN,0.0,Hartport,Czech Republic,60550.66
357,370,807,50.63,142.23,Operative full-range forecast,1,370,54.0,1.0,Timothymouth,Czech Republic,61228.96
409,422,913,56.91,146.44,Team-oriented executive core,1,422,29.0,1.0,Port Melissastad,Czech Republic,69428.73


***Задача 18***

Для объединённого датафрейма с пользователями, которые кликнули на рекламное сообщение `success_full_df`, выведите строки с данными пользователей из страны, название которой встречается чаще остальных, они проводят в интернете в среднем больше 120 минут и их возраст меньше 30 лет.
Cохраните получившиеся строки в новый датафрейм `filtered_df`.


In [55]:
top_country = success_full_df['Country'].value_counts().idxmax()
filtered_df = success_full_df[
    (success_full_df['Country'] == top_country)
    & (success_full_df['Daily Internet Usage'] > 120)
    & (success_full_df['Age'] < 30)
]
filtered_df

,level_0,index,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad,Number,Age,Male,City,Country,Area Income
99,108,206,49.95,136.59,Cloned object-oriented benchmark,1,108,21.0,1.0,Sanchezmouth,Czech Republic,48376.14
409,422,913,56.91,146.44,Team-oriented executive core,1,422,29.0,1.0,Port Melissastad,Czech Republic,69428.73


***Задача 19***

Для получившегося датафрейма `filtered_df` выведите строки с данными пользователей, для которых либо не указано среднее время, проведённое на сайте, либо указанное время больше 55 минут. Cохраните получившиеся строки в новый датафрейм `filtered_df2`.


In [56]:
filtered_df2 = filtered_df[
    filtered_df['Daily Time Spent on Site'].isna()
    | (filtered_df['Daily Time Spent on Site'] > 55)
]
filtered_df2

,level_0,index,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad,Number,Age,Male,City,Country,Area Income
409,422,913,56.91,146.44,Team-oriented executive core,1,422,29.0,1.0,Port Melissastad,Czech Republic,69428.73


**Дополнительные задачи**

***Задача 20***

Для датафрейма `adv123_df` выведите строки с данными, заголовок рекламного сообщения в которых включает слово `model`.

Для этого вам понадобится метод [`contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html).

Cохраните получившиеся строки в новый датафрейм `model_df`.


In [57]:
model_df = adv123_df[adv123_df['Ad Topic Line'].str.contains('model', case=False, na=False)]
model_df

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
53,44.98,129.31,Organized global model,1
108,69.00,NaN,Virtual composite model,0
185,78.57,NaN,Exclusive client-driven model,0
192,76.90,212.67,Synchronized multimedia model,0
288,NaN,161.16,Extended interactive model,1
324,65.77,NaN,Function-based fault-tolerant model,0
471,81.10,216.49,Front-line dynamic model,0
508,91.43,209.91,Organic motivating model,0
594,78.17,192.27,Automated mobile model,0
672,81.90,225.47,Multi-channeled 3rdgeneration model,0


***Задача 21***

Для получившегося датафрейма `model_df` выведите строки с данными пользователей, которые проводят на сайте больше среднего времени по всем пользователям в данном датафрейме. Cохраните получившиеся строки в новый датафрейм `model_popular_df`.


In [58]:
model_popular_df = model_df[model_df['Daily Time Spent on Site'] > model_df['Daily Time Spent on Site'].mean()]
model_popular_df

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
185,78.57,NaN,Exclusive client-driven model,0
192,76.90,212.67,Synchronized multimedia model,0
471,81.10,216.49,Front-line dynamic model,0
508,91.43,209.91,Organic motivating model,0
594,78.17,192.27,Automated mobile model,0
672,81.90,225.47,Multi-channeled 3rdgeneration model,0
823,81.98,212.88,Up-sized maximized model,0


***Задача 22***

Для объединённого датафрейма `model_popular_df` выведите строки с данными пользователей, номера которых равны 501, 712 и 823.

Для этого вам понадобится метод [`isin`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html).

*Подсказка:* Не забудьте, что номера пользователей находятся не в обычной колонке, а в колонке, являющейся индексом, поэтому вам необходимо получить значения индекса, а не обычной колонки.

In [59]:
target_numbers = [501, 712, 823]
model_popular_df[model_popular_df.index.isin(target_numbers)]

,Daily Time Spent on Site,Daily Internet Usage,Ad Topic Line,Clicked on Ad
823,81.98,212.88,Up-sized maximized model,0
